# fly.toml app configuration file generated for vercel-nest-aged-cherry-5429 on 2024-11-09T11:33:55-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vercel-nest-aged-cherry-5429'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
